//= require dependsOn
window.prepareDependsOn = ->
  for element in $('.depends-on')

    if $(element).data('name')
      field_to_check = $(element).data('name')
      field_to_check = "[name='#{field_to_check}']"
    else
      field_to_check = $(element).data('id')
      field_to_check = "##{field_to_check}"
    type = ($(field_to_check).attr('type'))
    if $(element).data('qualifier')
      depend_type = $(element).data('qualifier')
    else
      switch type
        when 'checkbox' then depend_type = 'checked'
        when 'text', 'number', 'select', 'radio' then depend_type = 'values'
    value =  $(element).data('value')
    if depend_type == 'match'
      value = RegExp(value)
    object = {}
    object[field_to_check] = {
      "#{depend_type}": value

    }
    $(element).dependsOn object

# ---
# generated by js2coffee 2.1.0
